### ISSUE TITLE
[Feature] Analyze only

### ISSUE THREAD

**Issue by LeagueRaINi** [namazso/IDAShell#3]
A context menu entry for the batch mode from idat(64) would be sweet in cases where u want to only let it analyze for later, the cli version also seems to a bit faster when it comes to analyzing

I'd add it myself but i have honestly no idea how this method of adding context menu entries works

**Comment by namazso** [comment]
after some consideration i decided not to add this. there are many many more interesting command line parameters that one could use and they really aren't the scope of this project, for now.
eventually i might switch to a more flexible model where you can just add as many executables with parameters as you want, but that time is not now.
just use a short script or modify this yourself
